server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/1023c07_GRUPO5
    username: 1023c07_GRUPO5
    password: cai1Eing
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
mail:
  password: notasprestadasdh
cloud:
  aws:
    credentials:
      access-key: "AKIAY3PLHSUJHCLH2EPX"
      secret-key: "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"
    region:
      static: us-east-2
    stack:
      auto: false

application:
  security:
    jwt:
      secret-key: 1092309uas90d8a90238209EXAMPLEKEY23092329309a809a8sd
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: notasprestadas@gmail.com

      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
