name: Conexión a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código de backend
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Copia de archivos a Amazon EC2
        run: |
          scp -i private_key.pem -r ./ ec2-user@52.201.124.42:/var/www/

      - name: SSH para EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.201.124.42
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}  # Using 'key' instead of 'key_file'
          script: |
            sudo systemctl restart httpd
