name: Conexión a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código de backend
        uses: actions/checkout@v2
      
      - name: Set up de Java
        uses: actions/setup-java@v2
        with:
          java-version: 17 
          distribution: 'adopt'

      - name: Build con Maven
        run: mvn clean package
        working-directory: ./

      - name: Decodificar key
        run: echo ${{ secrets.PRIVATE_KEY }} | base64 --decode > $HOME/.ssh/private_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Agregar clave del host al archivo known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan 52.201.124.42 >> $HOME/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Copia de archivos a Amazon EC2
        run: |
          chmod 600 $HOME/.ssh/private_key.pem
          scp -i $HOME/.ssh/private_key.pem ./target/security-0.0.1-SNAPSHOT.jar ec2-user@52.201.124.42:/var/www/
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: SSH para EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.201.124.42
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www
            java -jar security-0.0.1-SNAPSHOT.jar
