name: Conexión a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código de backend
        uses: actions/checkout@v2
      
      - name: Set up de Java
        uses: actions/setup-java@v2
        with:
          java-version: 17 
          distribution: 'adopt'

      - name: Build con Maven
        run: mvn clean package
        working-directory: ./

      - name: Copia de archivos a Amazon EC2
        run: |
          scp -i ${{ secrets.PRIVATE_KEY }} ./target/security-0.0.1-SNAPSHOT.jar ec2-user@52.201.124.42:/var/www/
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: SSH para EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.201.124.42
          username: ec2-user
          key_file: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www
            java -jar security-0.0.1-SNAPSHOT.jar
