name: Conexión a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código de backend
        uses: actions/checkout@v2
      
      - name: Set up de Java
        uses: actions/setup-java@v2
        with:
          java-version: 17 
          distribution: 'adopt'

      - name: Build con Maven
        run: mvn clean package
        working-directory: ./

      - name: Decodificación de la key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > $HOME/.ssh/1023c07-grupo5.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Actualización de permisos de la key
        run: chmod 600 $HOME/.ssh/1023c07-grupo5.pem

      - name: Agregar la key para SSH
        run: ssh-add $HOME/.ssh/1023c07-grupo5.pem

      - name: Agregar clave del host al archivo known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan 52.201.124.42 >> $HOME/.ssh/known_hosts

      - name: Copia de archivos a Amazon EC2 y conexión SSH
        run: |
          scp -i $HOME/.ssh/1023c07-grupo5.pem ./target/security-0.0.1-SNAPSHOT.jar ec2-user@52.201.124.42:/var/www/
          ssh -i $HOME/.ssh/1023c07-grupo5.pem ec2-user@52.201.124.42 "cd /var/www && java -jar security-0.0.1-SNAPSHOT.jar"
